import type { NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../components/Layout/Navbar";
import { NewsContainer } from "../components/news/NewsContainer";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>News Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />

      <main>
        <NewsContainer />
      </main>
    </div>
  );
};

export default Home;
